dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.2.0
  - OpenZeppelin/openzeppelin-contracts@4.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0'
dotenv: .env
networks:
  default: development
  harmony-main:
    eth_usd_price_feed: '0xbaf7C8149D586055ed02c286367A41E0aDA96b7C'
    verify: True
  harmony-test3:
    eth_usd_price_feed: '0x4f11696cE92D78165E1F8A9a4192444087a45b64'
    verify: False 
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
  expenseWallet: ${EXPENSE_WALLET}
  stakingWallet: ${STAKING_WALLET}
  liquidityWallet: ${LIQUIDITY_WALLET}
  recipient: ${RECIPIENT}

